samplesheet:
    samplesheet.tsv

workdir:
    /data/yuk5/project/1.FPDMM/01.WES/Pipe_210329

references:
    species:  homo_sapiens
    release:  99
    build:    hg38
    fasta:    /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Homo_sapiens_assembly38.fasta
    bwaidx:   /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Homo_sapiens_assembly38.fasta
    fadict:   /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Homo_sapiens_assembly38.fasta.dict
    itvlist:  /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/wgs_evaluation_regions.hg38.interval_list
    wesbed:   /data/yuk5/pipeline/wxs_phase1/ref/IDT_xGen_Exome_Research_Panel/hg38/xGen_Exome_Research_Panel.targets.hg38.bed
    flankbed: /data/yuk5/pipeline/wxs_phase1/ref/IDT_xGen_Exome_Research_Panel/hg38/xGen_Exome_Research_Panel.targets.withflank150.hg38.bed
    flankitv: /data/yuk5/pipeline/wxs_phase1/ref/IDT_xGen_Exome_Research_Panel/hg38/xGen_Exome_Research_Panel.targets.withflank150.hg38.bed.intervals
    interval: 17
    gatk_dbsnp:  /data/yuk5/pipeline/wgs_germline/ref/Homo_sapiens_assembly38.dbsnp138.vcf.gz
    gatk_1000g:  /data/yuk5/pipeline/wgs_germline/ref/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    gatk_indel:  /data/yuk5/pipeline/wgs_germline/ref/Homo_sapiens_assembly38.known_indels.vcf.gz
    gatk_axiom:  /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
    gatk_hapmap: /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/hapmap_3.3.hg38.vcf.gz
    gatk_omni:   /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/1000G_omni2.5.hg38.vcf.gz
    gatk_1000hc: /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz
    scramblefa: /data/yuk5/pipeline/wgs_germline/ref/SCRAMBLE/Homo_sapiens_assembly38.fasta
modules:
    bwa: bwa/0.7.17
    samtools: samtools/1.9
    picard: picard/2.17.11
    sambamba: sambamba/0.8.0
    samblaster: samblaster/0.1.25
    gatk: GATK/4.2.0.0
    vcftools: vcftools/0.1.16
    ucsc: ucsc/411
    bedtools: bedtools/2.30.0
    lofreq: lofreq/2.1.5
    python27: python/2.7
    python37: python/3.7
    freebayes: freebayes/1.3.5
    vcflib: vcflib/1.0.1
    cnvkit: cnvkit/0.9.8
    scramble: Scramble/1.0.1
bins:
    fastp: /data/yuk5/script/fastp
    vcfanno: /data/yuk5/pipeline/vcf_annotation/vcf_annotation.v1.wxs.py
simg:
    scramble: /usr/local/apps/Scramble/1.0.1-32893ef/libexec/scramble-1.0.1-32893ef.sif
max-jobs-per-second: 1
latency-wait: 120
keep-going: true
