samplesheet:
    samplesheet.combine.tsv

workdir:
    /data/RUNX1/project/1.FPDMM/01.WES/Pipe_230614

references:
    species:  homo_sapiens
    release:  99
    build:    hg38
    fasta:    /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Homo_sapiens_assembly38.fasta
    bwaidx:   /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Homo_sapiens_assembly38.fasta
    fadict:   /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Homo_sapiens_assembly38.fasta.dict
    itvlist:  /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/wgs_evaluation_regions.hg38.interval_list
    wesbed:   /data/yuk5/pipeline/wxs_phase1/ref/IDT_xGen_Exome_Research_Panel/hg38/xGen_Exome_Research_Panel.targets.hg38.bed
    flankbed: /data/yuk5/pipeline/wxs_phase1/ref/IDT_xGen_Exome_Research_Panel/hg38/xGen_Exome_Research_Panel.targets.withflank150.hg38.bed
    flankbedgz: /data/yuk5/pipeline/wxs_phase1/ref/IDT_xGen_Exome_Research_Panel/hg38/xGen_Exome_Research_Panel.targets.withflank150.hg38.bed.gz
    flankitv: /data/yuk5/pipeline/wxs_phase1/ref/IDT_xGen_Exome_Research_Panel/hg38/xGen_Exome_Research_Panel.targets.withflank150.hg38.bed.intervals
    interval: 17
    gatk_dbsnp:  /data/yuk5/pipeline/wgs_germline/ref/Homo_sapiens_assembly38.dbsnp138.vcf.gz
    gatk_1000g:  /data/yuk5/pipeline/wgs_germline/ref/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    gatk_indel:  /data/yuk5/pipeline/wgs_germline/ref/Homo_sapiens_assembly38.known_indels.vcf.gz
    gatk_axiom:  /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz
    gatk_hapmap: /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/hapmap_3.3.hg38.vcf.gz
    gatk_omni:   /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/1000G_omni2.5.hg38.vcf.gz
    gatk_1000hc: /data/yuk5/pipeline/wgs_germline/ref/gatk_bundle_hg38_v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz
    scramblefa: /data/yuk5/pipeline/wgs_germline/ref/SCRAMBLE/Homo_sapiens_assembly38.fasta
    cnvkitpon: /data/RUNX1/project/1.FPDMM/01.WES/PoN/210406/cnvkit/pon.cnn
modules:
    singularity: singularity
bins:
    vcfanno: scripts/vcf_annotation.v1.wxs.py
    gatk3: /data/yuk5/app/GATK_3.8-1/GenomeAnalysisTK.jar
    picardjar: /usr/local/share/picard-2.18.27-0/picard.jar
simg:
    bedtools:  singularity/bedtools_2.30.0.simg
    bwa:  singularity/bwa_0.7.17.simg
    cnvkit:  singularity/cnvkit_0.9.8.simg
    fastp:  singularity/fastp_0.20.1.simg
    freebayes:  singularity/freebayes_1.3.5.simg
    gatk:  singularity/gatk_3.8.simg
    gatk:  singularity/gatk_4.2.0.0.simg
    picard: singularity/picard_2.18.27.simg
    lofreq:  singularity/lofreq_2.1.5.simg
    manta:  singularity/manta_1.5.0.simg
    python2:  singularity/python_2.7.simg
    python3:  singularity/v3.9_with_pandas_vcfparser_latest.simg
    sambamba:  singularity/sambamba_0.8.0.simg
    samblaster:  singularity/samblaster_0.1.25.simg
    samtools:  singularity/samtools_1.9.simg
    scramble:  singularity/scramble_1.0.2.simg
    strelka:  singularity/strelka_2.9.2.simg
    vcflib:  singularity/vcflib_1.0.1.simg
    vcftools:  singularity/vcftools_0.1.16.simg
    mosdepth:  singularity/mosdepth_0.3.3.simg
    #scramble: /usr/local/apps/Scramble/1.0.1-32893ef/libexec/scramble-1.0.1-32893ef.sif
    #cnvkit: /data/yuk5/app/CNVKIT/cnvkit_0.9.8.sif
max-jobs-per-second: 1
latency-wait: 120
keep-going: true

# singularity
singularity: singularity exec -B /data,/vf,/gs9,/gpfs,/fdb,/spin1,/lscratch
